---
dist: focal
language: python
os: linux
services:
  - docker
jobs:
  include:
  - &ansible-2_9_27
    python: 3.9
    install:
      - pip install pipenv
      - rm Pipfile*
      - pipenv install -r test-requirements-ansible-2.9.27.txt --skip-lock
    env:
      - MOLECULE_DISTRO=debian:bullseye-slim
  - <<: *ansible-2_9_27
    env:
      - MOLECULE_DISTRO=debian:buster-slim
  - &ansible_10
    python: 3.11
    install:
      - pip install pipenv
      - rm Pipfile*
      - pipenv install -r test-requirements-ansible-10.txt --skip-lock
    env:
      - MOLECULE_DISTRO=debian:bullseye-slim
  - <<: *ansible_10
    env:
      - MOLECULE_DISTRO=debian:buster-slim
script:
  - pipenv run molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
