---

- name: Consul | Install dependencies
  ansible.builtin.include_tasks: install_dependencies.yml
  when: consul_keystore_install_dependencies | bool
  tags:
    - consul_keystore_configure
    - consul_keystore_install_dependencies

- name: Consul | Set fact consul_backup_properties
  ansible.builtin.set_fact:
    consul_backup_all_properties: []
    consul_set_properties: []

- name: Consul | Keys yml files
  ansible.builtin.include_tasks: "manage_keys_{{ (file.name | basename).split('.') | last }}_file.yml"
  run_once: true
  vars:
    consul_keystore_properties_file: "{{ file.name }}"
    consul_keystore_properties_file_name: "{{ file.name | basename | splitext | first }}"
    consul_keystore_properties_file_format: "{{ file.format }}"
    consul_keystore_properties_key: "{{ file.key is defined | ternary(file.key, 'data') }}"
  loop: "{{ consul_keystore_properties_files | flatten(levels=1) }}"
  loop_control:
    loop_var: file
  tags:
    - consul_keystore_configure
  when: consul_keystore_name is defined

- name: Consul | Delete diff keys
  ansible.builtin.consul_kv:
    host: "{{ consul_keystore_server }}"
    port: "{{ consul_keystore_http_port }}"
    token: "{{ consul_keystore_acl_token }}"
    key: "{{ key }}"
    state: absent
  loop: "{{ consul_backup_all_properties | difference(consul_set_properties) }}"
  loop_control:
    loop_var: key
  when:
    - consul_backup_all_properties | length > 0
    - consul_set_properties is defined
    - consul_set_properties | length > 0
