---

- name: "Consul | Check {{ consul_keystore_properties_path }}/{{ consul_keystore_properties_file }}"
  ansible.builtin.stat:
    path: "{{ consul_keystore_properties_path }}/{{ consul_keystore_properties_file }}"
  delegate_to: localhost
  become: false
  changed_when: false
  register: consul_check_yaml_file

- name: Set consul_to_upload_properties empty to avoid error between plays
  ansible.builtin.set_fact:
    consul_to_upload_properties: {}

- name: Consul | Manage keys from {{ consul_keystore_properties_path }}/{{ consul_keystore_properties_file }} KV
  when: consul_check_yaml_file.stat.exists and consul_keystore_properties_file_format == 'kv'
  block:
    - name: Read local properties
      ansible.builtin.include_vars:
        file: "{{ consul_keystore_properties_path + '/' + consul_keystore_properties_file }}"
        name: consul_yaml_file

    - name: Set consul_key_separator
      ansible.builtin.set_fact:
        consul_key_separator: "{{ (consul_keystore_expand_keys == True) | ternary('/', '.') }}"

    - name: Set consul_key_parent
      ansible.builtin.set_fact:
        consul_key_parent: "{{ consul_keystore_mountpoint + '/' + consul_keystore_name + '/' + consul_keystore_properties_file_name }}"

    - name: Set consul_to_upload_properties
      ansible.builtin.set_fact:
        consul_to_upload_properties: "{{ consul_yaml_file | flatten_collection(sep=consul_key_separator) }}"

    - name: Update consul_setted_properties
      ansible.builtin.set_fact:
        consul_set_properties: "{{ consul_set_properties + ([consul_key_parent + '/'] | product(consul_to_upload_properties.keys()) | map('join')) | list }}"

    - name: "Consul | Read properties for {{ consul_key_parent }}"
      ansible.builtin.consul_kv:
        host: "{{ consul_keystore_server }}"
        port: "{{ consul_keystore_http_port }}"
        token: "{{ consul_keystore_acl_token }}"
        key: "{{ consul_key_parent + '/' }}"
        recurse: true
        state: present
      register: consul_backup_properties

    - name: Set consul_backup_keys
      ansible.builtin.set_fact:
        consul_backup_keys: "{{ consul_backup_properties.data | map(attribute='Key') | list | filter | list }}"

    - name: Update consul_backup_keys expanded
      ansible.builtin.set_fact:
        consul_backup_keys: "{{ consul_backup_keys | map('regex_replace', '\\.', '/') | list }}"
      when: consul_keystore_expand_keys

    - name: Update consul_backup_all_keys
      ansible.builtin.set_fact:
        consul_backup_all_properties: "{{ consul_backup_all_properties + consul_backup_keys }}"

    - name: "Consul | Upload / Update properties for {{ consul_key_parent }}"
      ansible.builtin.consul_kv:
        host: "{{ consul_keystore_server }}"
        port: "{{ consul_keystore_http_port }}"
        token: "{{ consul_keystore_acl_token }}"
        key: "{{ consul_key_parent + '/' + ((consul_keystore_expand_keys == True) | ternary(property.key | regex_replace('\\.', '/'), property.key)) }}"
        value: "{{ (property.value | bool) | ternary(property.value | lower, property.value) }}"
      with_dict: "{{ consul_to_upload_properties }}"
      loop_control:
        loop_var: property

- name: "Consul | Manage keys file from {{ consul_keystore_properties_path }}/{{ consul_keystore_properties_file }}"
  when: consul_check_yaml_file.stat.exists and consul_keystore_properties_file_format == 'file'
  block:
    - name: Set consul_to_upload_properties
      ansible.builtin.set_fact:
        consul_to_upload_properties: "{{ lookup('file', consul_keystore_properties_path + '/' + consul_keystore_properties_file) }}"

    - name: Set consul_key_parent
      ansible.builtin.set_fact:
        consul_key_parent: "{{ consul_keystore_mountpoint + '/' + consul_keystore_name + '/' + consul_keystore_properties_file_name }}"

    - name: Update consul_backup_all_keys
      ansible.builtin.set_fact:
        consul_set_properties: "{{ consul_set_properties + [consul_key_parent + '/' + consul_keystore_properties_key] }}"

    - name: "Consul | Read properties for {{ consul_key_parent }}"
      ansible.builtin.consul_kv:
        host: "{{ consul_keystore_server }}"
        port: "{{ consul_keystore_http_port }}"
        token: "{{ consul_keystore_acl_token }}"
        key: "{{ consul_key_parent + '/' }}"
        recurse: true
        state: present
      register: consul_backup_properties

    - name: Set consul_backup_keys
      ansible.builtin.set_fact:
        consul_backup_keys: "{{ consul_backup_properties.data | map(attribute='Key') | list | filter | list }}"

    - name: Update consul_backup_keys expanded
      ansible.builtin.set_fact:
        consul_backup_keys: "{{ consul_backup_keys | map('regex_replace', '\\.', '/') | list }}"
      when: consul_keystore_expand_keys

    - name: Update consul_backup_all_keys
      ansible.builtin.set_fact:
        consul_backup_all_properties: "{{ consul_backup_all_properties + consul_backup_keys }}"

    - name: "Consul | Upload / Update properties for {{ consul_key_parent }} properties"
      ansible.builtin.consul_kv:
        host: "{{ consul_keystore_server }}"
        port: "{{ consul_keystore_http_port }}"
        token: "{{ consul_keystore_acl_token }}"
        key: "{{ consul_key_parent + '/' + consul_keystore_properties_key }}"
        value: "{{ consul_to_upload_properties }}"
