---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint . &&
  ansible-lint .

platforms:
  - name: consul-test
    groups:
      - consul
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    published_ports:
      - "8500:8500"
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    cgroupns_mode: host
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible
  log: true

scenario:
  name: default

verifier:
  name: ansible
