---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint -f colored .
  ansible-lint --force-color .

platforms:
  - name: consul01
    groups:
      - consul
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /run/lock
    published_ports:
      - "8500:8500"
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: "RTMIN+3"

provisioner:
  name: ansible
verifier:
  name: ansible
