---

- name: Prepare
  hosts: consul
  tasks:
    - name: Install rsyslog
      ansible.builtin.include_role:
        name: rsyslog
    - name: Install consul
      ansible.builtin.include_role:
        name: consul
